# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - node-app-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_948ff8df72c44baf8ee7176c7d7dea62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_93cf9c4e692440df89f72aa1651c49d8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_948ff8df72c44baf8ee7176c7d7dea62 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'node-app-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_890399c20eb2418daaad8e330d06b8be }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_948ff8df72c44baf8ee7176c7d7dea62 }}/appsvc/staticsite:${{ github.sha }}'